FROM node:24-alpine as dependencies
WORKDIR /app
COPY package*.json ./
RUN npm ci


FROM node:24-alpine AS production
WORKDIR /app
COPY --from=dependencies /app/node_modules ./node_modules
COPY . . 
EXPOSE 3000
CMD ["node", "server.js"]